// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/agent/script"
)

type FakeJobScriptProvider struct {
	GetStub        func(jobName string, relativePath string) script.Script
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		jobName      string
		relativePath string
	}
	getReturns struct {
		result1 script.Script
	}
}

func (fake *FakeJobScriptProvider) Get(jobName string, relativePath string) script.Script {
	fake.getMutex.Lock()
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		jobName      string
		relativePath string
	}{jobName, relativePath})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(jobName, relativePath)
	} else {
		return fake.getReturns.result1
	}
}

func (fake *FakeJobScriptProvider) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeJobScriptProvider) GetArgsForCall(i int) (string, string) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].jobName, fake.getArgsForCall[i].relativePath
}

func (fake *FakeJobScriptProvider) GetReturns(result1 script.Script) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 script.Script
	}{result1}
}

var _ script.JobScriptProvider = new(FakeJobScriptProvider)
