---
platform: linux

inputs:
- name: agent-info
- name: bosh-agent

params:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:
  BOSH_ENVIRONMENT:
  JUMPBOX_PRIVATE_KEY:
  JUMPBOX_USERNAME:
  JUMPBOX_IP:
  GINKGO_SEED:

run:
  path: bosh-agent/ci/tasks/test-integration.sh

