// Code generated by counterfeiter. DO NOT EDIT.
package firewallfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/platform/firewall"
)

type FakeManager struct {
	CleanupStub        func() error
	cleanupMutex       sync.RWMutex
	cleanupArgsForCall []struct {
	}
	cleanupReturns struct {
		result1 error
	}
	cleanupReturnsOnCall map[int]struct {
		result1 error
	}
	SetupMonitFirewallStub        func() error
	setupMonitFirewallMutex       sync.RWMutex
	setupMonitFirewallArgsForCall []struct {
	}
	setupMonitFirewallReturns struct {
		result1 error
	}
	setupMonitFirewallReturnsOnCall map[int]struct {
		result1 error
	}
	SetupNATSFirewallStub        func(string) error
	setupNATSFirewallMutex       sync.RWMutex
	setupNATSFirewallArgsForCall []struct {
		arg1 string
	}
	setupNATSFirewallReturns struct {
		result1 error
	}
	setupNATSFirewallReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManager) Cleanup() error {
	fake.cleanupMutex.Lock()
	ret, specificReturn := fake.cleanupReturnsOnCall[len(fake.cleanupArgsForCall)]
	fake.cleanupArgsForCall = append(fake.cleanupArgsForCall, struct {
	}{})
	stub := fake.CleanupStub
	fakeReturns := fake.cleanupReturns
	fake.recordInvocation("Cleanup", []interface{}{})
	fake.cleanupMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) CleanupCallCount() int {
	fake.cleanupMutex.RLock()
	defer fake.cleanupMutex.RUnlock()
	return len(fake.cleanupArgsForCall)
}

func (fake *FakeManager) CleanupCalls(stub func() error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = stub
}

func (fake *FakeManager) CleanupReturns(result1 error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = nil
	fake.cleanupReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) CleanupReturnsOnCall(i int, result1 error) {
	fake.cleanupMutex.Lock()
	defer fake.cleanupMutex.Unlock()
	fake.CleanupStub = nil
	if fake.cleanupReturnsOnCall == nil {
		fake.cleanupReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cleanupReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) SetupMonitFirewall() error {
	fake.setupMonitFirewallMutex.Lock()
	ret, specificReturn := fake.setupMonitFirewallReturnsOnCall[len(fake.setupMonitFirewallArgsForCall)]
	fake.setupMonitFirewallArgsForCall = append(fake.setupMonitFirewallArgsForCall, struct {
	}{})
	stub := fake.SetupMonitFirewallStub
	fakeReturns := fake.setupMonitFirewallReturns
	fake.recordInvocation("SetupMonitFirewall", []interface{}{})
	fake.setupMonitFirewallMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) SetupMonitFirewallCallCount() int {
	fake.setupMonitFirewallMutex.RLock()
	defer fake.setupMonitFirewallMutex.RUnlock()
	return len(fake.setupMonitFirewallArgsForCall)
}

func (fake *FakeManager) SetupMonitFirewallCalls(stub func() error) {
	fake.setupMonitFirewallMutex.Lock()
	defer fake.setupMonitFirewallMutex.Unlock()
	fake.SetupMonitFirewallStub = stub
}

func (fake *FakeManager) SetupMonitFirewallReturns(result1 error) {
	fake.setupMonitFirewallMutex.Lock()
	defer fake.setupMonitFirewallMutex.Unlock()
	fake.SetupMonitFirewallStub = nil
	fake.setupMonitFirewallReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) SetupMonitFirewallReturnsOnCall(i int, result1 error) {
	fake.setupMonitFirewallMutex.Lock()
	defer fake.setupMonitFirewallMutex.Unlock()
	fake.SetupMonitFirewallStub = nil
	if fake.setupMonitFirewallReturnsOnCall == nil {
		fake.setupMonitFirewallReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setupMonitFirewallReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) SetupNATSFirewall(arg1 string) error {
	fake.setupNATSFirewallMutex.Lock()
	ret, specificReturn := fake.setupNATSFirewallReturnsOnCall[len(fake.setupNATSFirewallArgsForCall)]
	fake.setupNATSFirewallArgsForCall = append(fake.setupNATSFirewallArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetupNATSFirewallStub
	fakeReturns := fake.setupNATSFirewallReturns
	fake.recordInvocation("SetupNATSFirewall", []interface{}{arg1})
	fake.setupNATSFirewallMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManager) SetupNATSFirewallCallCount() int {
	fake.setupNATSFirewallMutex.RLock()
	defer fake.setupNATSFirewallMutex.RUnlock()
	return len(fake.setupNATSFirewallArgsForCall)
}

func (fake *FakeManager) SetupNATSFirewallCalls(stub func(string) error) {
	fake.setupNATSFirewallMutex.Lock()
	defer fake.setupNATSFirewallMutex.Unlock()
	fake.SetupNATSFirewallStub = stub
}

func (fake *FakeManager) SetupNATSFirewallArgsForCall(i int) string {
	fake.setupNATSFirewallMutex.RLock()
	defer fake.setupNATSFirewallMutex.RUnlock()
	argsForCall := fake.setupNATSFirewallArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeManager) SetupNATSFirewallReturns(result1 error) {
	fake.setupNATSFirewallMutex.Lock()
	defer fake.setupNATSFirewallMutex.Unlock()
	fake.SetupNATSFirewallStub = nil
	fake.setupNATSFirewallReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) SetupNATSFirewallReturnsOnCall(i int, result1 error) {
	fake.setupNATSFirewallMutex.Lock()
	defer fake.setupNATSFirewallMutex.Unlock()
	fake.SetupNATSFirewallStub = nil
	if fake.setupNATSFirewallReturnsOnCall == nil {
		fake.setupNATSFirewallReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setupNATSFirewallReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ firewall.Manager = new(FakeManager)
