// Code generated by counterfeiter. DO NOT EDIT.
package firewallfakes

import (
	"net"
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/platform/firewall"
)

type FakeDNSResolver struct {
	LookupIPStub        func(string) ([]net.IP, error)
	lookupIPMutex       sync.RWMutex
	lookupIPArgsForCall []struct {
		arg1 string
	}
	lookupIPReturns struct {
		result1 []net.IP
		result2 error
	}
	lookupIPReturnsOnCall map[int]struct {
		result1 []net.IP
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDNSResolver) LookupIP(arg1 string) ([]net.IP, error) {
	fake.lookupIPMutex.Lock()
	ret, specificReturn := fake.lookupIPReturnsOnCall[len(fake.lookupIPArgsForCall)]
	fake.lookupIPArgsForCall = append(fake.lookupIPArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.LookupIPStub
	fakeReturns := fake.lookupIPReturns
	fake.recordInvocation("LookupIP", []interface{}{arg1})
	fake.lookupIPMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDNSResolver) LookupIPCallCount() int {
	fake.lookupIPMutex.RLock()
	defer fake.lookupIPMutex.RUnlock()
	return len(fake.lookupIPArgsForCall)
}

func (fake *FakeDNSResolver) LookupIPCalls(stub func(string) ([]net.IP, error)) {
	fake.lookupIPMutex.Lock()
	defer fake.lookupIPMutex.Unlock()
	fake.LookupIPStub = stub
}

func (fake *FakeDNSResolver) LookupIPArgsForCall(i int) string {
	fake.lookupIPMutex.RLock()
	defer fake.lookupIPMutex.RUnlock()
	argsForCall := fake.lookupIPArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDNSResolver) LookupIPReturns(result1 []net.IP, result2 error) {
	fake.lookupIPMutex.Lock()
	defer fake.lookupIPMutex.Unlock()
	fake.LookupIPStub = nil
	fake.lookupIPReturns = struct {
		result1 []net.IP
		result2 error
	}{result1, result2}
}

func (fake *FakeDNSResolver) LookupIPReturnsOnCall(i int, result1 []net.IP, result2 error) {
	fake.lookupIPMutex.Lock()
	defer fake.lookupIPMutex.Unlock()
	fake.LookupIPStub = nil
	if fake.lookupIPReturnsOnCall == nil {
		fake.lookupIPReturnsOnCall = make(map[int]struct {
			result1 []net.IP
			result2 error
		})
	}
	fake.lookupIPReturnsOnCall[i] = struct {
		result1 []net.IP
		result2 error
	}{result1, result2}
}

func (fake *FakeDNSResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDNSResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ firewall.DNSResolver = new(FakeDNSResolver)
