// Code generated by counterfeiter. DO NOT EDIT.
package firewallfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/v2/platform/firewall"
)

type FakeNatsFirewallHook struct {
	BeforeConnectStub        func(string) error
	beforeConnectMutex       sync.RWMutex
	beforeConnectArgsForCall []struct {
		arg1 string
	}
	beforeConnectReturns struct {
		result1 error
	}
	beforeConnectReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNatsFirewallHook) BeforeConnect(arg1 string) error {
	fake.beforeConnectMutex.Lock()
	ret, specificReturn := fake.beforeConnectReturnsOnCall[len(fake.beforeConnectArgsForCall)]
	fake.beforeConnectArgsForCall = append(fake.beforeConnectArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.BeforeConnectStub
	fakeReturns := fake.beforeConnectReturns
	fake.recordInvocation("BeforeConnect", []interface{}{arg1})
	fake.beforeConnectMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNatsFirewallHook) BeforeConnectCallCount() int {
	fake.beforeConnectMutex.RLock()
	defer fake.beforeConnectMutex.RUnlock()
	return len(fake.beforeConnectArgsForCall)
}

func (fake *FakeNatsFirewallHook) BeforeConnectCalls(stub func(string) error) {
	fake.beforeConnectMutex.Lock()
	defer fake.beforeConnectMutex.Unlock()
	fake.BeforeConnectStub = stub
}

func (fake *FakeNatsFirewallHook) BeforeConnectArgsForCall(i int) string {
	fake.beforeConnectMutex.RLock()
	defer fake.beforeConnectMutex.RUnlock()
	argsForCall := fake.beforeConnectArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeNatsFirewallHook) BeforeConnectReturns(result1 error) {
	fake.beforeConnectMutex.Lock()
	defer fake.beforeConnectMutex.Unlock()
	fake.BeforeConnectStub = nil
	fake.beforeConnectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNatsFirewallHook) BeforeConnectReturnsOnCall(i int, result1 error) {
	fake.beforeConnectMutex.Lock()
	defer fake.beforeConnectMutex.Unlock()
	fake.BeforeConnectStub = nil
	if fake.beforeConnectReturnsOnCall == nil {
		fake.beforeConnectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.beforeConnectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNatsFirewallHook) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNatsFirewallHook) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ firewall.NatsFirewallHook = new(FakeNatsFirewallHook)
