Vagrant.configure(2) do |config|
  config.vm.box = "greenhouse/bosh-integration"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
  config.vm.base_mac = "0800271AAAAA"

  config.vm.provision "shell", inline: <<-SHELL
    C:\\vagrant\\bosh-agent.exe -P windows -C C:\\vagrant\\agent.json
  SHELL

end
