Vagrant.configure(2) do |config|
  config.vm.box = "https://s3.amazonaws.com/bosh-windows-integration/bosh-agent.windows-integration.box"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.provider :virtualbox do |v, override|
    override.vm.network :private_network, ip: '192.168.60.4', id: :local
  end
	

  config.vm.provision "shell", inline: <<-SHELL
		if ($(C:\\vagrant\\service_wrapper.exe status) -ne "NonExistent") {
			if ($(C:\\vagrant\\service_wrapper.exe status) -eq "Started") {
				C:\\vagrant\\service_wrapper.exe stop
			}

			C:\\vagrant\\service_wrapper.exe uninstall
		}
		C:\\vagrant\\service_wrapper.exe install
		C:\\vagrant\\service_wrapper.exe start
  SHELL

end
