// This file was generated by counterfeiter
package scriptfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-agent/agent/script"
	"github.com/cloudfoundry/bosh-agent/agent/script/drain"
)

type FakeJobScriptProvider struct {
	NewScriptStub        func(jobName string, scriptName string, options map[string]interface{}) script.Script
	newScriptMutex       sync.RWMutex
	newScriptArgsForCall []struct {
		jobName    string
		scriptName string
		options    map[string]interface{}
	}
	newScriptReturns struct {
		result1 script.Script
	}
	NewDrainScriptStub        func(jobName string, params drain.ScriptParams) script.CancellableScript
	newDrainScriptMutex       sync.RWMutex
	newDrainScriptArgsForCall []struct {
		jobName string
		params  drain.ScriptParams
	}
	newDrainScriptReturns struct {
		result1 script.CancellableScript
	}
	NewParallelScriptStub        func(scriptName string, scripts []script.Script) script.CancellableScript
	newParallelScriptMutex       sync.RWMutex
	newParallelScriptArgsForCall []struct {
		scriptName string
		scripts    []script.Script
	}
	newParallelScriptReturns struct {
		result1 script.CancellableScript
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJobScriptProvider) NewScript(jobName string, scriptName string, options map[string]interface{}) script.Script {
	fake.newScriptMutex.Lock()
	fake.newScriptArgsForCall = append(fake.newScriptArgsForCall, struct {
		jobName    string
		scriptName string
		options    map[string]interface{}
	}{jobName, scriptName, options})
	fake.recordInvocation("NewScript", []interface{}{jobName, scriptName, options})
	fake.newScriptMutex.Unlock()
	if fake.NewScriptStub != nil {
		return fake.NewScriptStub(jobName, scriptName, options)
	} else {
		return fake.newScriptReturns.result1
	}
}

func (fake *FakeJobScriptProvider) NewScriptCallCount() int {
	fake.newScriptMutex.RLock()
	defer fake.newScriptMutex.RUnlock()
	return len(fake.newScriptArgsForCall)
}

func (fake *FakeJobScriptProvider) NewScriptArgsForCall(i int) (string, string, map[string]interface{}) {
	fake.newScriptMutex.RLock()
	defer fake.newScriptMutex.RUnlock()
	return fake.newScriptArgsForCall[i].jobName, fake.newScriptArgsForCall[i].scriptName, fake.newScriptArgsForCall[i].options
}

func (fake *FakeJobScriptProvider) NewScriptReturns(result1 script.Script) {
	fake.NewScriptStub = nil
	fake.newScriptReturns = struct {
		result1 script.Script
	}{result1}
}

func (fake *FakeJobScriptProvider) NewDrainScript(jobName string, params drain.ScriptParams) script.CancellableScript {
	fake.newDrainScriptMutex.Lock()
	fake.newDrainScriptArgsForCall = append(fake.newDrainScriptArgsForCall, struct {
		jobName string
		params  drain.ScriptParams
	}{jobName, params})
	fake.recordInvocation("NewDrainScript", []interface{}{jobName, params})
	fake.newDrainScriptMutex.Unlock()
	if fake.NewDrainScriptStub != nil {
		return fake.NewDrainScriptStub(jobName, params)
	} else {
		return fake.newDrainScriptReturns.result1
	}
}

func (fake *FakeJobScriptProvider) NewDrainScriptCallCount() int {
	fake.newDrainScriptMutex.RLock()
	defer fake.newDrainScriptMutex.RUnlock()
	return len(fake.newDrainScriptArgsForCall)
}

func (fake *FakeJobScriptProvider) NewDrainScriptArgsForCall(i int) (string, drain.ScriptParams) {
	fake.newDrainScriptMutex.RLock()
	defer fake.newDrainScriptMutex.RUnlock()
	return fake.newDrainScriptArgsForCall[i].jobName, fake.newDrainScriptArgsForCall[i].params
}

func (fake *FakeJobScriptProvider) NewDrainScriptReturns(result1 script.CancellableScript) {
	fake.NewDrainScriptStub = nil
	fake.newDrainScriptReturns = struct {
		result1 script.CancellableScript
	}{result1}
}

func (fake *FakeJobScriptProvider) NewParallelScript(scriptName string, scripts []script.Script) script.CancellableScript {
	var scriptsCopy []script.Script
	if scripts != nil {
		scriptsCopy = make([]script.Script, len(scripts))
		copy(scriptsCopy, scripts)
	}
	fake.newParallelScriptMutex.Lock()
	fake.newParallelScriptArgsForCall = append(fake.newParallelScriptArgsForCall, struct {
		scriptName string
		scripts    []script.Script
	}{scriptName, scriptsCopy})
	fake.recordInvocation("NewParallelScript", []interface{}{scriptName, scriptsCopy})
	fake.newParallelScriptMutex.Unlock()
	if fake.NewParallelScriptStub != nil {
		return fake.NewParallelScriptStub(scriptName, scripts)
	} else {
		return fake.newParallelScriptReturns.result1
	}
}

func (fake *FakeJobScriptProvider) NewParallelScriptCallCount() int {
	fake.newParallelScriptMutex.RLock()
	defer fake.newParallelScriptMutex.RUnlock()
	return len(fake.newParallelScriptArgsForCall)
}

func (fake *FakeJobScriptProvider) NewParallelScriptArgsForCall(i int) (string, []script.Script) {
	fake.newParallelScriptMutex.RLock()
	defer fake.newParallelScriptMutex.RUnlock()
	return fake.newParallelScriptArgsForCall[i].scriptName, fake.newParallelScriptArgsForCall[i].scripts
}

func (fake *FakeJobScriptProvider) NewParallelScriptReturns(result1 script.CancellableScript) {
	fake.NewParallelScriptStub = nil
	fake.newParallelScriptReturns = struct {
		result1 script.CancellableScript
	}{result1}
}

func (fake *FakeJobScriptProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newScriptMutex.RLock()
	defer fake.newScriptMutex.RUnlock()
	fake.newDrainScriptMutex.RLock()
	defer fake.newDrainScriptMutex.RUnlock()
	fake.newParallelScriptMutex.RLock()
	defer fake.newParallelScriptMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeJobScriptProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ script.JobScriptProvider = new(FakeJobScriptProvider)
